WIP: Calendar Selection Option
uwblueprint/KidsAbility pull request #174
Opened 2019-06-28 00:28 UTC by KarolinaXin

Still working on it

2019-07-03 03:44 UTC, gregmaxin requested changes
- The package.json file needs to be updated. Use npm install --save {name} to have it saved to the package.json automatically

2019-07-15 18:42 UTC, Ruxuan reviewed
Need to add `react-calendar-multiday`, `react-day-picker`, `reactjs-popup` to the package.json

2019-07-15 18:42 UTC, Ruxuan commented on src/pages/Search/Search.js
> +      this.setState({selectedDates: []});
```
this.setState({
  locations: locations,
  location: locations[0],
  selectedDates: [],
  from: undefined,
  to: undefined
})
```

2019-07-15 18:42 UTC, Ruxuan commented on src/pages/Search/Search.js
> +    console.log("YOLO");
Remove `console.log` lines

2019-07-15 18:42 UTC, Ruxuan commented on src/pages/Search/Search.js
> +                  {this.handleDateOptionDisplay(selectDates.value)}
The default value of `selectDates.value` is `dayOfWeek` which causes a popup. So when a user first navigates to this page, the popup is shown.
<img width="1624" alt="Screenshot 2019-07-15 14 32 08" src="https://user-images.githubusercontent.com/10586811/61239630-5e4c8f80-a70d-11e9-8c78-f1910f1ec9a6.png">

2019-07-15 18:42 UTC, Ruxuan commented on src/pages/Search/Search.js
> +              <div className="headingRow"> Day of the Week </div>
I think the "Day of the week" div should be inside of `<Popup>` then you can remove the `<>`
<img width="354" alt="Screenshot 2019-07-15 14 38 30" src="https://user-images.githubusercontent.com/10586811/61240018-3c074180-a70e-11e9-8516-7653cf23ff55.png">

2019-07-15 18:42 UTC, Ruxuan commented on src/pages/Search/Search.js
> +              <Popup open = {selectedDateValue === 'individualDates'} position="right center">
I'm a bit confused here. Is there a reason why `individualDates` pops up but `dateRange` doesn't?

2019-07-24 03:45 UTC, closed without merging